### ISSUE TITLE
Need input encoding in xsl file

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/awesome-matlab-notebook#2]
The Powers That Be at Mathworks have decided that printing variables should be done using the Unicode U+00D7 symbol. This means that the `.xsl` stylesheet needs to load

```latex
\usepackage[utf8x]{inputenc}
\DeclareUnicodeCharacter{0215}{\ensuremath{\times}}
```

You will get this error if you do not do this:

```matlab
! Package inputenc Error: Unicode character × (U+00D7)
(inputenc)                not set up for use with LaTeX.
```

[Here](https://nickhigham.wordpress.com/2017/01/30/good-times-in-matlab/) is a blog post on the subject.

**Comment by sg-s** [comment]
god help us. so just include this in the stylesheet? send me a PR

**Comment by alec-hoyland** [comment]
Not sure yet. I'm still debugging. I will submit a PR when I'm sure it works.

**Comment by alec-hoyland** [comment]
Here's the problem: latex doesn't do unicode. Specifically, the pdflatex engine doesn't do unicode. You can trick it on a case by case basis, by using `\DeclareUnicodeCharacter{}{}` to replace one pattern with another, but this doesn't seem to work inside of `verbatim` blocks, which Mathworks, in their infinite wisdom, have decided is the best way to represent their output.

I imagine part of the reason that this hasn't been fixed is that they've been really pushing their `.mlx` live scripts (which are egregiously slow, and don't work on GNU/Linux machines if not also macs). 

The only solution I have found is to not use  pdflatex. If you use xelatex instead, which is unicode-compatible, you don't have this problem. So, the actual solution is to change the `pdflatex` command (line 122 of `pdflib.make`) to use `xelatex` instead. 

Since xelatex is bundled with TeX Live, MacTeX, MiKTeX, and Lyx, there shouldn't be a problem with the toolchain.
